module Ecommerce
  module Countries
    ISO = {
      'Afghanistan' =>                                      {:code => 'AF', :eu => false},
      'Albania' =>                                          {:code => 'AL', :eu => false},
      'Algeria' =>                                          {:code => 'DZ', :eu => false},
      'American Samoa' =>                                   {:code => 'AS', :eu => false},
      'Andorra' =>                                          {:code => 'AD', :eu => false},
      'Angola' =>                                           {:code => 'AO', :eu => false},
      'Anguilla' =>                                         {:code => 'AI', :eu => false},
      'Antarctica' =>                                       {:code => 'AQ', :eu => false},
      'Antigua And Barbuda' =>                              {:code => 'AG', :eu => false},
      'Argentina' =>                                        {:code => 'AR', :eu => false},
      'Armenia' =>                                          {:code => 'AM', :eu => false},
      'Aruba' =>                                            {:code => 'AW', :eu => false},
      'Australia' =>                                        {:code => 'AU', :eu => false},
      'Austria' =>                                          {:code => 'AT', :eu => true},
      'Azerbaijan' =>                                       {:code => 'AZ', :eu => false},
      'Bahamas' =>                                          {:code => 'BS', :eu => false},
      'Bahrain' =>                                          {:code => 'BH', :eu => false},
      'Bangladesh' =>                                       {:code => 'BD', :eu => false},
      'Barbados' =>                                         {:code => 'BB', :eu => false},
      'Belarus' =>                                          {:code => 'BY', :eu => false},
      'Belgium' =>                                          {:code => 'BE', :eu => true},
      'Belize' =>                                           {:code => 'BZ', :eu => false},
      'Benin' =>                                            {:code => 'BJ', :eu => false},
      'Bermuda' =>                                          {:code => 'BM', :eu => false},
      'Bhutan' =>                                           {:code => 'BT', :eu => false},
      'Bolivia' =>                                          {:code => 'BO', :eu => false},
      'Bosnia And Herzegowina' =>                           {:code => 'BA', :eu => false},
      'Botswana' =>                                         {:code => 'BW', :eu => false},
      'Bouvet Island' =>                                    {:code => 'BV', :eu => false},
      'Brazil' =>                                           {:code => 'BR', :eu => false},
      'British Indian Ocean Territory' =>                   {:code => 'IO', :eu => false},
      'Brunei Darussalam' =>                                {:code => 'BN', :eu => false},
      'Bulgaria' =>                                         {:code => 'BG', :eu => true},
      'Burkina Faso' =>                                     {:code => 'BF', :eu => false},
      'Burundi' =>                                          {:code => 'BI', :eu => false},
      'Cambodia' =>                                         {:code => 'KH', :eu => false},
      'Cameroon' =>                                         {:code => 'CM', :eu => false},
      'Canada' =>                                           {:code => 'CA', :eu => false},
      'Cape Verde' =>                                       {:code => 'CV', :eu => false},
      'Cayman Islands' =>                                   {:code => 'KY', :eu => false},
      'Central African Republic' =>                         {:code => 'CF', :eu => false},
      'Chad' =>                                             {:code => 'TD', :eu => false},
      'Chile' =>                                            {:code => 'CL', :eu => false},
      'China' =>                                            {:code => 'CN', :eu => false},
      'Colombia' =>                                         {:code => 'CO', :eu => false},
      'Comoros' =>                                          {:code => 'KM', :eu => false},
      'Congo' =>                                            {:code => 'CG', :eu => false},
      'Cook Islands' =>                                     {:code => 'CK', :eu => false},
      'Costa Rica' =>                                       {:code => 'CR', :eu => false},
      "Cote D'ivoire" =>                                    {:code => 'CI', :eu => false},
      'Croatia (Local Name: Hrvatska)' =>                   {:code => 'HR', :eu => false},
      'Cuba' =>                                             {:code => 'CU', :eu => false},
      'Cyprus' =>                                           {:code => 'CY', :eu => true},
      'Czech Republic' =>                                   {:code => 'CZ', :eu => true},
      'Denmark' =>                                          {:code => 'DK', :eu => true},
      'Djibouti' =>                                         {:code => 'DJ', :eu => false},
      'Dominica' =>                                         {:code => 'DM', :eu => false},
      'Dominican Republic' =>                               {:code => 'DO', :eu => false},
      'East Timor' =>                                       {:code => 'TP', :eu => false},
      'Ecuador' =>                                          {:code => 'EC', :eu => false},
      'Egypt' =>                                            {:code => 'EG', :eu => false},
      'El Salvador' =>                                      {:code => 'SV', :eu => false},
      'Equatorial Guinea' =>                                {:code => 'GQ', :eu => false},
      'Eritrea' =>                                          {:code => 'ER', :eu => false},
      'Estonia' =>                                          {:code => 'EE', :eu => true},
      'Ethiopia' =>                                         {:code => 'ET', :eu => false},
      'Falkland Islands (Malvinas)' =>                      {:code => 'FK', :eu => false},
      'Faroe Islands' =>                                    {:code => 'FO', :eu => false},
      'Fiji' =>                                             {:code => 'FJ', :eu => false},
      'Finland' =>                                          {:code => 'FI', :eu => true},
      'France' =>                                           {:code => 'FR', :eu => true},
      'France, Metropolitan'    =>                          {:code => 'FX', :eu => false},
      'French Guiana' =>                                    {:code => 'GF', :eu => false},
      'French Polynesia' =>                                 {:code => 'PF', :eu => false},
      'French Southern Territories' =>                      {:code => 'TF', :eu => false},
      'Gabon' =>                                            {:code => 'GA', :eu => false},
      'Gambia' =>                                           {:code => 'GM', :eu => false},
      'Georgia' =>                                          {:code => 'GE', :eu => false},
      'Germany' =>                                          {:code => 'DE', :eu => true},
      'Ghana' =>                                            {:code => 'GH', :eu => false},
      'Gibraltar' =>                                        {:code => 'GI', :eu => false},
      'Greece' =>                                           {:code => 'GR', :eu => true},
      'Greenland' =>                                        {:code => 'GL', :eu => false},
      'Grenada' =>                                          {:code => 'GD', :eu => false},
      'Guadeloupe' =>                                       {:code => 'GP', :eu => false},
      'Guam' =>                                             {:code => 'GU', :eu => false},
      'Guatemala' =>                                        {:code => 'GT', :eu => false},
      'Guinea' =>                                           {:code => 'GN', :eu => false},
      'Guinea-Bissau' =>                                    {:code => 'GW', :eu => false},
      'Guyana' =>                                           {:code => 'GY', :eu => false},
      'Haiti' =>                                            {:code => 'HT', :eu => false},
      'Heard And Mc Donald Islands' =>                      {:code => 'HM', :eu => false},
      'Honduras' =>                                         {:code => 'HN', :eu => false},
      'Hong Kong' =>                                        {:code => 'HK', :eu => false},
      'Hungary' =>                                          {:code => 'HU', :eu => true},
      'Iceland' =>                                          {:code => 'IS', :eu => false},
      'India' =>                                            {:code => 'IN', :eu => false},
      'Indonesia' =>                                        {:code => 'ID', :eu => false},
      'Iran (Islamic Republic Of)' =>                       {:code => 'IR', :eu => false},
      'Iraq' =>                                             {:code => 'IQ', :eu => false},
      'Ireland' =>                                          {:code => 'IE', :eu => true},
      'Israel' =>                                           {:code => 'IL', :eu => false},
      'Italy' =>                                            {:code => 'IT', :eu => true},
      'Jamaica' =>                                          {:code => 'JM', :eu => false},
      'Japan' =>                                            {:code => 'JP', :eu => false},
      'Jordan' =>                                           {:code => 'JO', :eu => false},
      'Kazakhstan' =>                                       {:code => 'KZ', :eu => false},
      'Kenya' =>                                            {:code => 'KE', :eu => false},
      'Kiribati' =>                                         {:code => 'KI', :eu => false},
      "Korea, Democratic People's Republic Of" =>           {:code => 'KP', :eu => false},
      'Korea, Republic Of'    =>                            {:code => 'KR', :eu => false},
      'Kuwait' =>                                           {:code => 'KW', :eu => false},
      'Kyrgyzstan' =>                                       {:code => 'KG', :eu => false},
      "Lao People's Democratic Republic" =>                 {:code => 'LA', :eu => false},
      'Latvia' =>                                           {:code => 'LV', :eu => true},
      'Lebanon' =>                                          {:code => 'LB', :eu => false},
      'Lesotho' =>                                          {:code => 'LS', :eu => false},
      'Liberia' =>                                          {:code => 'LR', :eu => false},
      'Libyan Arab Jamahiriya' =>                           {:code => 'LY', :eu => false},
      'Liechtenstein' =>                                    {:code => 'LI', :eu => false},
      'Lithuania' =>                                        {:code => 'LT', :eu => true},
      'Luxembourg' =>                                       {:code => 'LU', :eu => true},
      'Macau' =>                                            {:code => 'MO', :eu => false},
      'Macedonia, The Former Yugoslav Republic Of'    =>    {:code => 'MK', :eu => false},
      'Madagascar' =>                                       {:code => 'MG', :eu => false},
      'Malawi' =>                                           {:code => 'MW', :eu => false},
      'Malaysia' =>                                         {:code => 'MY', :eu => false},
      'Maldives' =>                                         {:code => 'MV', :eu => false},
      'Mali' =>                                             {:code => 'ML', :eu => false},
      'Malta' =>                                            {:code => 'MT', :eu => true},
      'Marshall Islands' =>                                 {:code => 'MH', :eu => false},
      'Martinique' =>                                       {:code => 'MQ', :eu => false},
      'Mauritania' =>                                       {:code => 'MR', :eu => false},
      'Mauritius' =>                                        {:code => 'MU', :eu => false},
      'Mayotte' =>                                          {:code => 'YT', :eu => false},
      'Mexico' =>                                           {:code => 'MX', :eu => false},
      'Micronesia, Federated States Of' =>                  {:code => 'FM', :eu => false},
      'Moldova, Republic Of' =>                             {:code => 'MD', :eu => false},
      'Monaco' =>                                           {:code => 'MC', :eu => false},
      'Mongolia' =>                                         {:code => 'MN', :eu => false},
      'Montserrat' =>                                       {:code => 'MS', :eu => false},
      'Morocco' =>                                          {:code => 'MA', :eu => false},
      'Mozambique' =>                                       {:code => 'MZ', :eu => false},
      'Myanmar' =>                                          {:code => 'MM', :eu => false},
      'Namibia' =>                                          {:code => 'NA', :eu => false},
      'Nauru' =>                                            {:code => 'NR', :eu => false},
      'Nepal' =>                                            {:code => 'NP', :eu => false},
      'Netherlands' =>                                      {:code => 'NL', :eu => true},
      'Netherlands Antilles' =>                             {:code => 'AN', :eu => false},
      'New Caledonia' =>                                    {:code => 'NC', :eu => false},
      'New Zealand' =>                                      {:code => 'NZ', :eu => false},
      'Nicaragua' =>                                        {:code => 'NI', :eu => false},
      'Niger' =>                                            {:code => 'NE', :eu => false},
      'Nigeria' =>                                          {:code => 'NG', :eu => false},
      'Niue' =>                                             {:code => 'NU', :eu => false},
      'Norfolk Island' =>                                   {:code => 'NF', :eu => false},
      'Northern Mariana Islands' =>                         {:code => 'MP', :eu => false},
      'Norway' =>                                           {:code => 'NO', :eu => false},
      'Oman' =>                                             {:code => 'OM', :eu => false},
      'Pakistan' =>                                         {:code => 'PK', :eu => false},
      'Palau' =>                                            {:code => 'PW', :eu => false},
      'Panama' =>                                           {:code => 'PA', :eu => false},
      'Papua New Guinea' =>                                 {:code => 'PG', :eu => false},
      'Paraguay' =>                                         {:code => 'PY', :eu => false},
      'Peru' =>                                             {:code => 'PE', :eu => false},
      'Philippines' =>                                      {:code => 'PH', :eu => false},
      'Pitcairn' =>                                         {:code => 'PN', :eu => false},
      'Poland' =>                                           {:code => 'PL', :eu => true},
      'Portugal' =>                                         {:code => 'PT', :eu => true},
      'Puerto Rico' =>                                      {:code => 'PR', :eu => false},
      'Qatar' =>                                            {:code => 'QA', :eu => false},
      'Reunion' =>                                          {:code => 'RE', :eu => false},
      'Romania' =>                                          {:code => 'RO', :eu => true},
      'Russian Federation' =>                               {:code => 'RU', :eu => false},
      'Rwanda' =>                                           {:code => 'RW', :eu => false},
      'Saint Kitts And Nevis' =>                            {:code => 'KN', :eu => false},
      'Saint Lucia' =>                                      {:code => 'LC', :eu => false},
      'Saint Vincent And The Grenadines' =>                 {:code => 'VC', :eu => false},
      'Samoa' =>                                            {:code => 'WS', :eu => false},
      'San Marino' =>                                       {:code => 'SM', :eu => false},
      'Sao Tome And Principe' =>                            {:code => 'ST', :eu => false},
      'Saudi Arabia' =>                                     {:code => 'SA', :eu => false},
      'Senegal' =>                                          {:code => 'SN', :eu => false},
      'Seychelles' =>                                       {:code => 'SC', :eu => false},
      'Sierra Leone' =>                                     {:code => 'SL', :eu => false},
      'Singapore' =>                                        {:code => 'SG', :eu => false},
      'Slovakia (Slovak Republic)' =>                       {:code => 'SK', :eu => true},
      'Slovenia' =>                                         {:code => 'SI', :eu => true},
      'Solomon Islands' =>                                  {:code => 'SB', :eu => false},
      'Somalia' =>                                          {:code => 'SO', :eu => false},
      'South Africa' =>                                     {:code => 'ZA', :eu => false},
      'South Georgia And The South Sandwich Islands' =>     {:code => 'GS', :eu => false},
      'Spain' =>                                            {:code => 'ES', :eu => true},
      'Sri Lanka' =>                                        {:code => 'LK', :eu => false},
      'St. Helena' =>                                       {:code => 'SH', :eu => false},
      'St. Pierre And Miquelon' =>                          {:code => 'PM', :eu => false},
      'Sudan' =>                                            {:code => 'SD', :eu => false},
      'Suriname' =>                                         {:code => 'SR', :eu => false},
      'Svalbard And Jan Mayen Islands' =>                   {:code => 'SJ', :eu => false},
      'Swaziland' =>                                        {:code => 'SZ', :eu => false},
      'Sweden' =>                                           {:code => 'SE', :eu => true},
      'Switzerland' =>                                      {:code => 'CH', :eu => false},
      'Syrian Arab Republic' =>                             {:code => 'SY', :eu => false},
      'Taiwan' =>                                           {:code => 'TW', :eu => false},
      'Tajikistan' =>                                       {:code => 'TJ', :eu => false},
      'Tanzania, United Republic Of' =>                     {:code => 'TZ', :eu => false},
      'Thailand' =>                                         {:code => 'TH', :eu => false},
      'Togo' =>                                             {:code => 'TG', :eu => false},
      'Tokelau' =>                                          {:code => 'TK', :eu => false},
      'Tonga' =>                                            {:code => 'TO', :eu => false},
      'Trinidad And Tobago' =>                              {:code => 'TT', :eu => false},
      'Tunisia' =>                                          {:code => 'TN', :eu => false},
      'Turkey' =>                                           {:code => 'TR', :eu => false},
      'Turkmenistan' =>                                     {:code => 'TM', :eu => false},
      'Turks And Caicos Islands' =>                         {:code => 'TC', :eu => false},
      'Tuvalu' =>                                           {:code => 'TV', :eu => false},
      'Uganda' =>                                           {:code => 'UG', :eu => false},
      'Ukraine' =>                                          {:code => 'UA', :eu => false},
      'United Arab Emirates' =>                             {:code => 'AE', :eu => false},
      'United Kingdom' =>                                   {:code => 'GB', :eu => true},
      'United States' =>                                    {:code => 'US', :eu => false},
      'United States Minor Outlying Islands' =>             {:code => 'UM', :eu => false},
      'Uruguay' =>                                          {:code => 'UY', :eu => false},
      'Uzbekistan' =>                                       {:code => 'UZ', :eu => false},
      'Vanuatu' =>                                          {:code => 'VU', :eu => false},
      'Vatican City State (Holy See)' =>                    {:code => 'VA', :eu => false},
      'Venezuela' =>                                        {:code => 'VE', :eu => false},
      'Viet Nam' =>                                         {:code => 'VN', :eu => false},
      'Virgin Islands (British)' =>                         {:code => 'VG', :eu => false},
      'Virgin Islands (U.S.)' =>                            {:code => 'VI', :eu => false},
      'Wallis And Futuna Islands' =>                        {:code => 'WF', :eu => false},
      'Western Sahara' =>                                   {:code => 'EH', :eu => false},
      'Yemen' =>                                            {:code => 'YE', :eu => false},
      'Yugoslavia' =>                                       {:code => 'YU', :eu => false},
      'Zaire' =>                                            {:code => 'ZR', :eu => false},
      'Zambia' =>                                           {:code => 'ZM', :eu => false},
      'Zimbabwe' =>                                         {:code => 'ZW', :eu => false}
    }
    
    class << self
      def iso
        ISO.map { |name, details| [name, details[:code]] }.sort
      end
      
      def in_eu?(location)
        country = ISO.find { |name, details| details[:code] == location }
        return false if country.nil?
        
        country[1][:eu]
      end
    end
  end
end